INSERT INTO CATEGORIES(CATEGORY_NAME) VALUES('ARRECADACAO');
INSERT INTO CATEGORIES(CATEGORY_NAME) VALUES('DISTRIBUICAO');
INSERT INTO CATEGORIES(CATEGORY_NAME) VALUES('VENDA');

INSERT INTO EVENTS(ADDRESS, CATEGORY_ID, DESCRIPTION, DATE_EVENT, TIME_START, TIME_END, STATUS) VALUES('Parque Infantil - Centro', 1, 'Venda local de doces caseiros, diretamente na barraca VIVA', '2022-12-17', '09:00:00', '17:00:00', 'CONFIRMADO');
INSERT INTO EVENTS(ADDRESS, CATEGORY_ID, DESCRIPTION, DATE_EVENT, TIME_START, TIME_END, STATUS) VALUES('Praça Pedro de Toledo - Centro', 2,'Distribuição de almoço no local para nossos amigos desafortunados. Toda ajuda será bem-vinda', '2022-12-18', '10:00:00', '15:00:00', 'CONFIRMADO');
